CREATE TABLE IF NOT EXISTS focus_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(255),
    duration_seconds INT,
    status VARCHAR(20) DEFAULT 'RUNNING',
    started_at TIMESTAMP,
    expected_end_at TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_experience BIGINT DEFAULT 0,
    cultivation_rank VARCHAR(255) DEFAULT 'Mortal'
);
